# workflow의 이름
name: Terraform AWS Deployment   
on:                                                  
  push:
    branches:
      - keem     # push 이벤트 발생 시 실행

# workflow 작업 정의     
jobs:                            
  check:            
    runs-on: ubuntu-latest  
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name : Setup Terraform
        uses : hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6
    
      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Plan
        run: terraform plan -no-color
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

#      - name: Terraform Destroy
#        run: terraform destroy -auto-approve
